export const endpoints = {
  authSignIn: "/api/auth/signin",
  authVerify: "/api/auth/verify",
  authGoogle: "/api/auth/google",
  authGoogleCode: "/api/auth/google/code",
  authRefresh: "/api/auth/refresh",
  storesMe: "/api/stores/me",
  stores: "/api/stores",
  paymentConfig: "/api/stores/me/payment-config",
  notificationPreferences: "/api/stores/me/notification-preferences",
  pushToken: "/api/stores/me/push-token",
  products: "/api/products",
  categories: "/api/categories",
  industries: "/api/industries",
  orders: "/api/orders",
  customers: "/api/customers",
  uploadProductImages: "/api/uploads/product-images",
  whatsappChats: "/api/whatsapp/chats",
  whatsappSend: "/api/whatsapp/send",
  whatsappConnect: "/api/whatsapp/connect",
  whatsappConnectionStatus: "/api/whatsapp/connection-status",
  whatsappSync: "/api/whatsapp/sync",
  instagramConnect: "/api/instagram/connect",
  instagramConnectionStatus: "/api/instagram/connection-status",
  instagramSubscribeWebhooks: "/api/instagram/subscribe-webhooks",
  instagramChats: "/api/instagram/chats",
  instagramSend: "/api/instagram/send",
} as const;
