export const endpoints = {
  authSignIn: "/api/auth/signin",
  authVerify: "/api/auth/verify",
  authGoogle: "/api/auth/google",
  authGoogleCode: "/api/auth/google/code",
  authRefresh: "/api/auth/refresh",
  storesMe: "/api/stores/me",
  stores: "/api/stores",
  paymentConfig: "/api/stores/me/payment-config",
  paymentConfigRazorpayTestCheckout: "/api/stores/me/payment-config/razorpay/test-checkout",
  paymentConfigRazorpayVerifyTest: "/api/stores/me/payment-config/razorpay/verify-test",
  notificationPreferences: "/api/stores/me/notification-preferences",
  pushToken: "/api/stores/me/push-token",
  products: "/api/products",
  categories: "/api/categories",
  industries: "/api/industries",
  orders: "/api/orders",
  customers: "/api/customers",
  uploadProductImages: "/api/uploads/product-images",
  whatsappChats: "/api/whatsapp/chats",
  whatsappSend: "/api/whatsapp/send",
  whatsappConnect: "/api/whatsapp/connect",
  whatsappConnectionStatus: "/api/whatsapp/connection-status",
  whatsappSync: "/api/whatsapp/sync",
  instagramConnect: "/api/instagram/connect",
  instagramConnectionStatus: "/api/instagram/connection-status",
  instagramSubscribeWebhooks: "/api/instagram/subscribe-webhooks",
  instagramChats: "/api/instagram/chats",
  instagramSend: "/api/instagram/send",
  subscriptionsPricing: "/api/subscriptions/pricing",
  subscriptionsCheckout: "/api/subscriptions/checkout",
  subscriptionsVerify: "/api/subscriptions/verify",
  subscriptionsStatus: "/api/subscriptions/status",
  supportConversation: "/api/support/conversation",
  supportMessages: (conversationId: number) =>
    `/api/support/conversations/${conversationId}/messages`,
  supportEscalate: (conversationId: number) =>
    `/api/support/conversations/${conversationId}/escalate`,
  supportAdminMe: "/api/support/admin/me",
  supportAdminConversations: "/api/support/admin/conversations",
  supportAdminMessages: (conversationId: number) =>
    `/api/support/admin/conversations/${conversationId}/messages`,
  supportAdminReplyMode: (conversationId: number) =>
    `/api/support/admin/conversations/${conversationId}/reply-mode`,
  supportAdminClose: (conversationId: number) =>
    `/api/support/admin/conversations/${conversationId}/close`,
  supportUnread: "/api/support/unread",
  supportMarkRead: (conversationId: number) =>
    `/api/support/conversations/${conversationId}/read`,
  supportAdminSummary: "/api/support/admin/summary",
  supportAdminMarkRead: (conversationId: number) =>
    `/api/support/admin/conversations/${conversationId}/read`,
} as const;
